"""Generate PDF health reports."""

import io
from datetime import datetime


def generate_health_report(prediction_data, patient_info=None):
    """Generate a PDF health report and return bytes."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    story = []

    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.HexColor("#4f46e5"),
        spaceAfter=12,
    )
    heading_style = ParagraphStyle(
        "CustomHeading",
        parent=styles["Heading2"],
        fontSize=14,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=16,
        spaceAfter=8,
    )
    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#334155"),
    )

    pred = prediction_data.get("prediction", prediction_data)
    triage = prediction_data.get("triage", {})
    differential = prediction_data.get("differential_diagnosis", [])

    story.append(Paragraph("Health SymptomSense — Medical Report", title_style))
    story.append(Paragraph(f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}", body_style))
    story.append(Spacer(1, 0.2 * inch))

    summary_data = [
        ["Predicted Disease", pred.get("disease", "N/A")],
        ["Confidence", f"{pred.get('confidence', 0)}%"],
        ["Severity Score", str(pred.get("severity_score", 0))],
        ["Triage Level", triage.get("level", "ROUTINE")],
        ["Recommended Action", triage.get("action", "Consult healthcare provider")],
    ]
    if patient_info:
        if patient_info.get("age"):
            summary_data.append(["Patient Age", str(patient_info["age"])])
        if patient_info.get("gender"):
            summary_data.append(["Gender", patient_info["gender"]])

    summary_table = Table(summary_data, colWidths=[2.2 * inch, 4 * inch])
    summary_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f1f5f9")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(summary_table)
    story.append(Spacer(1, 0.15 * inch))

    symptoms = prediction_data.get("input", {}).get("symptoms", pred.get("symptoms", []))
    if symptoms:
        story.append(Paragraph("Reported Symptoms", heading_style))
        symptom_text = ", ".join(s.replace("_", " ").title() for s in symptoms)
        story.append(Paragraph(symptom_text, body_style))

    if pred.get("description"):
        story.append(Paragraph("Disease Description", heading_style))
        story.append(Paragraph(pred["description"][:2000], body_style))

    if differential:
        story.append(Paragraph("Differential Diagnosis (Top Alternatives)", heading_style))
        diff_data = [["Rank", "Disease", "Confidence"]]
        for d in differential:
            diff_data.append([str(d.get("rank", "")), d.get("disease", ""), f"{d.get('confidence', 0)}%"])
        diff_table = Table(diff_data, colWidths=[0.6 * inch, 3.5 * inch, 1.2 * inch])
        diff_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#4f46e5")),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e2e8f0")),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
        ]))
        story.append(diff_table)

    for section_title, key in [
        ("Precautions", "precautions"),
        ("Medications", "medications"),
        ("Dietary Recommendations", "diets"),
        ("Workout Plans", "workouts"),
    ]:
        items = pred.get(key, [])
        if items:
            story.append(Paragraph(section_title, heading_style))
            for item in items[:10]:
                story.append(Paragraph(f"• {item}", body_style))

    story.append(Spacer(1, 0.3 * inch))
    disclaimer = (
        "DISCLAIMER: This report is generated by an AI system for informational and educational "
        "purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult a qualified healthcare provider for medical concerns."
    )
    story.append(Paragraph(disclaimer, ParagraphStyle(
        "Disclaimer", parent=body_style, fontSize=8, textColor=colors.HexColor("#64748b")
    )))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
